
package com.example.main.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.16
 * Wed Jan 17 09:49:01 IST 2018
 * Generated source version: 3.0.16
 */

@XmlRootElement(name = "setNameResponse", namespace = "http://main.example.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "setNameResponse", namespace = "http://main.example.com/")

public class SetNameResponse {


}

